### ISSUE TITLE
Add f5totec explanation

### ISSUE THREAD

**Issue by A-Gray-94** [mdolab/MACHtutorial#18]
https://github.com/mdolab/MACHtutorial/blob/master/doc/struct_tacs.rst

It would be nice to add an explanation of how to use f5totec. Right now in the example code you write out a couple of f5 visualisation files but there is no explanation of how to actually visualise them.

**Comment by eirikurj** [comment]
You may have found this already. The syntax is _f5totec filename.f5_ This will generate .dat file with the same name. This file is then opened with tecplot.

I suggest you add a small exampe where you feel its appropriate and submit a PR.

**Comment by eirikurj** [comment]
Issue is resolved. Closing.
